import type { EndpointConfig } from '../types/api'

const waitForSelectorField = {
  name: 'waitForSelector',
  label: 'Wait for Selector',
  type: 'text' as const,
  placeholder: '#content',
  section: 'Advanced',
}

const rewriteUrlField = {
  name: 'rewriteUrl',
  label: 'Rewrite URL',
  type: 'text' as const,
  placeholder: 'https://example.com/rewritten',
  section: 'Advanced',
}

const gotoOptionsFields = [
  {
    name: 'gotoOptions.waitUntil',
    label: 'Wait Until',
    type: 'select' as const,
    options: [
      { label: 'load', value: 'load' },
      { label: 'domcontentloaded', value: 'domcontentloaded' },
      { label: 'networkidle0', value: 'networkidle0' },
      { label: 'networkidle2', value: 'networkidle2' },
    ],
    section: 'Advanced',
  },
  {
    name: 'gotoOptions.timeout',
    label: 'Goto Timeout (ms)',
    type: 'number' as const,
    placeholder: '30000',
    section: 'Advanced',
  },
]

export const endpoints: EndpointConfig[] = [
  {
    id: 'content',
    label: 'Content',
    method: 'POST',
    path: '/content',
    description: 'Get the rendered HTML content of a page',
    responseType: 'html',
    hasUrlHtmlInput: true,
    fields: [
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
  {
    id: 'screenshot',
    label: 'Screenshot',
    method: 'POST',
    path: '/screenshot',
    description: 'Take a screenshot of a page',
    responseType: 'image',
    contentType: 'image/png',
    hasUrlHtmlInput: true,
    fields: [
      {
        name: 'screenshotOptions.type',
        label: 'Image Type',
        type: 'select',
        options: [
          { label: 'png', value: 'png' },
          { label: 'jpeg', value: 'jpeg' },
          { label: 'webp', value: 'webp' },
        ],
        section: 'Screenshot Options',
      },
      {
        name: 'screenshotOptions.fullPage',
        label: 'Full Page',
        type: 'boolean',
        defaultValue: false,
        section: 'Screenshot Options',
      },
      {
        name: 'screenshotOptions.quality',
        label: 'Quality (1-100)',
        type: 'number',
        placeholder: '80',
        section: 'Screenshot Options',
        hint: 'Only for jpeg/webp',
      },
      {
        name: 'screenshotOptions.omitBackground',
        label: 'Omit Background',
        type: 'boolean',
        defaultValue: false,
        section: 'Screenshot Options',
      },
      {
        name: 'viewport.width',
        label: 'Viewport Width',
        type: 'number',
        placeholder: '1280',
        section: 'Viewport',
      },
      {
        name: 'viewport.height',
        label: 'Viewport Height',
        type: 'number',
        placeholder: '720',
        section: 'Viewport',
      },
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
  {
    id: 'pdf',
    label: 'PDF',
    method: 'POST',
    path: '/pdf',
    description: 'Generate a PDF of a page',
    responseType: 'pdf',
    contentType: 'application/pdf',
    hasUrlHtmlInput: true,
    fields: [
      {
        name: 'pdfOptions.format',
        label: 'Page Format',
        type: 'select',
        options: [
          { label: 'Letter', value: 'Letter' },
          { label: 'A4', value: 'A4' },
          { label: 'A3', value: 'A3' },
          { label: 'Legal', value: 'Legal' },
          { label: 'Tabloid', value: 'Tabloid' },
        ],
        section: 'PDF Options',
      },
      {
        name: 'pdfOptions.printBackground',
        label: 'Print Background',
        type: 'boolean',
        defaultValue: true,
        section: 'PDF Options',
      },
      {
        name: 'pdfOptions.landscape',
        label: 'Landscape',
        type: 'boolean',
        defaultValue: false,
        section: 'PDF Options',
      },
      {
        name: 'pdfOptions.scale',
        label: 'Scale',
        type: 'number',
        placeholder: '1',
        section: 'PDF Options',
      },
      {
        name: 'viewport.width',
        label: 'Viewport Width',
        type: 'number',
        placeholder: '1280',
        section: 'Viewport',
      },
      {
        name: 'viewport.height',
        label: 'Viewport Height',
        type: 'number',
        placeholder: '720',
        section: 'Viewport',
      },
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
  {
    id: 'json',
    label: 'JSON',
    method: 'POST',
    path: '/json',
    description: 'Extract structured JSON from a page using a prompt',
    responseType: 'json',
    hasUrlHtmlInput: true,
    fields: [
      {
        name: 'prompt',
        label: 'Prompt',
        type: 'textarea',
        placeholder: 'Extract the main heading and all links from this page',
        required: true,
        hint: 'Describe the data you want extracted',
      },
      {
        name: 'schema',
        label: 'JSON Schema',
        type: 'json',
        placeholder: '{"type": "object", "properties": {...}}',
        section: 'Advanced',
        hint: 'Optional JSON schema for the response',
      },
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
  {
    id: 'markdown',
    label: 'Markdown',
    method: 'POST',
    path: '/markdown',
    description: 'Convert a page to Markdown',
    responseType: 'markdown',
    hasUrlHtmlInput: true,
    fields: [
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
  {
    id: 'snapshot',
    label: 'Snapshot',
    method: 'POST',
    path: '/snapshot',
    description: 'Get HTML content and a base64 screenshot',
    responseType: 'snapshot',
    hasUrlHtmlInput: true,
    fields: [
      {
        name: 'viewport.width',
        label: 'Viewport Width',
        type: 'number',
        placeholder: '1280',
        section: 'Viewport',
      },
      {
        name: 'viewport.height',
        label: 'Viewport Height',
        type: 'number',
        placeholder: '720',
        section: 'Viewport',
      },
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
  {
    id: 'scrape',
    label: 'Scrape',
    method: 'POST',
    path: '/scrape',
    description: 'Scrape structured data from a page',
    responseType: 'json',
    hasUrlHtmlInput: true,
    fields: [
      {
        name: 'elements',
        label: 'Elements Config',
        type: 'json',
        placeholder: '[{"selector": "h1"}]',
        hint: 'Array of element selectors to scrape',
      },
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
  {
    id: 'links',
    label: 'Links',
    method: 'POST',
    path: '/links',
    description: 'Extract all links from a page',
    responseType: 'json',
    hasUrlHtmlInput: true,
    fields: [
      waitForSelectorField,
      rewriteUrlField,
      ...gotoOptionsFields,
    ],
  },
]
